### ISSUE TITLE
Page Titles

### ISSUE THREAD

**Issue by JHGrove3** [igrigorik/ga-beacon#10]
Is it possible to pass a page title to GA-Beacon, to make it easier to read some of the GA reports?

This could be done by adding a query string with the desired title.

http://ga-beacon.appspot.com/UA-XXXXXXX-1/path/page.htm?pixel&title=Tracked%20Page%20Title

**Comment by igrigorik** [comment]
You can initialize page title via: http://localhost:8080/account/UA-XXXXX-X/path-to/page?dt="Page Title"

**Comment by cmpsoares91** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- Carlos

Accept: https://www.linkedin.com/blink?simpleRedirect=c30MczkNejwOd3cMdPsTdzcVdjR4imVLqnhxt6BSrCACdAx5jmthdSQZumlbp6lOomxP9DhPpnlDnSlQqnpKqjRHpipxt6cJpnhFtCVFbnhPpnlDbmNJpjRDrCBHoS5Ot2pBt6BSrABDpl9BsD0ZoioScyROp6JCrTwTqiQNcTFJpPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5988748260158767104_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=0ScyROp6JCrTwTqiQNcTFJpPRAqmkCrTdElRsPojtfl4NRjDlvdz5WuB5Qgkx6kzBBl7tlgSRoq6xkrD5dk35Bs4FckTd6ozxDdSF8dD9zlAdfgR9jl45UdT1Ujjx3dkd1u6dlp3xmsCl5rjxBqmkSqn9PmCl9h7pcnQ9lcztkoT5jp7EMtzwUqnhQd79gu4x8dj1TuDF1sRdzmj9EtQxeljdzckZUu5l1gk5TtThpdPkMgQsRc4xhgjRAqmZI9DhPpnlDnSlQqnpKqjRHpiphdzdAhktElApOrkphgjRKpmJLl6hFripKtmMZt2oScyROp6JCrTwTqiQNcTFJpPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5988748260158767104_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=3wUdPgZp4BBr6dFt79x9DhPpnlDnSlQqnpKqjRHpipIsBlBoSBSsCljsClJrThPtmcZoioScyROp6JCrTwTqiQNcTFJpPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5988748260158767104_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
