### ISSUE TITLE
Transparent Pixel Tracker

### ISSUE THREAD

**Issue by erinzm** [igrigorik/ga-beacon#11]
It would be really nice to have a transparent pixel tracker option.
That could be useful on wiki pages &c.

**Comment by Himura2la** [comment]
Unfortunately, [this pixel](https://raw.githubusercontent.com/igrigorik/ga-beacon/master/static/pixel.gif) is not transperent:

![](https://raw.githubusercontent.com/igrigorik/ga-beacon/master/static/pixel.gif)

Maybe use the attached one from http://www.1x1px.me/ ?
![ffffff-0](https://user-images.githubusercontent.com/7802808/41854061-edf246c0-7897-11e8-8156-4c0abc358f39.png)
