### ISSUE TITLE
Direct traffic (robots?)

### ISSUE THREAD

**Issue by dencorg** [igrigorik/ga-beacon#12]
Hello,
I am using my own implementation of ga-beacon for my project in order to measure traffic to third party pages (mostly partners blogs).

The thing that puzzles me is that I observe a great amount of direct traffic to the img src link. I am trying to find the origin of that traffic and I believe that it may be caused by robots, since the measurement protocol is used to send the traffic data.
The google analytics support page mentions:

````````
The Google Analytics JavaScript only sends data to Google Analytics when JavaScript is enabled. Because most search engine robots do not activate JavaScript, robot traffic is not counted in Analytics when using a JavaScript tracking method.

If the search engine that crawls your site does activate JavaScript, or if you specifically configure your website server files to send the Analytics tracking beacon, you will receive search engine robot data in your reports.
`````````
Any suggestions for that matter? Should I only count the refferal traffic from the page the snippet is in, just to be safe? Is there another way to identify the nature of that traffic (and robots)?

Thanks for your work!

**Comment by igrigorik** [comment]
We do passthrough the user-agent string from the original client to GA, so I'd expect GA to handle this.. That said, you can add some additional logic on your side (within the beacon) to discard hits based on UA-string and/or any other signals. FWIW, might be worth investigating: http://www.lunametrics.com/blog/2013/09/05/filter-bots-google-analytics/
