### ISSUE TITLE
GA Real-Time disclaimer

### ISSUE THREAD

**Issue by thdoan** [igrigorik/ga-beacon#15]
There should be a disclaimer that GA Real-Time analytics is not actually in real time. In other words, once you have added the GA beacon, don't expect the numbers to pop up in the real-time analytics dashboard immediately. There is generally a lag of between a couple hours up to 24 hours before you can see your metrics. However, this might help:

http://blogote.com/ideas/forcing-google-analytics-to-show-real-time-data/168/

**Comment by arfoll** [comment]
For g-analytic n00bs like me it might be helpful to have this in the readme/instructions I thought it didn't work at first :)

**Comment by kshitijb** [comment]
@arfoll Me too. Wasted some time and then found this issue here. I will check again in 24 hours.
