### ISSUE TITLE
Support for Events

### ISSUE THREAD

**Issue by daniellmb** [igrigorik/ga-beacon#17]
I realize the main use-case is restricted applications where you don't have access to any JavaScript. But it 
could be useful to support other hit types such as [events](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) for times where a declarative setup is desired.

Perhaps an API such as:
`https://ga-beacon.appspot.com/UA-XXXXX-X/event?category=____&action=____&label=____&value=____`

This would allow projects like [MemSnap](https://github.com/daniellmb/MemSnap) to easily publish memory use statistics over time to Google, with a url like:

```JavaScript
memSnap(this, 'https://ga-beacon.appspot.com/UA-XXXXX-X/event?category=Mem&action=Snap&label={lbl}&value={use}
```

Thoughts?

**Comment by igrigorik** [comment]
Looks reasonable. If you beat me to it.. happy to accept a pull for it :)

**Comment by igrigorik** [comment]
Resolved in https://github.com/igrigorik/ga-beacon/commit/2173c8aedf304dbf4539cc4be754bb28f44ff44d. Note that I've changed the logic to be more generic: you can use query params to passthrough any values to the collector. 

To report an event, an example would be: http://localhost:8080/account/UA-XXXXX-X/event?t=event&ec=category&ea=action&el=label&ev=value

**Comment by daniellmb** [comment]
Sweet! I like how you changed it to use a simple loop without the parameter name mapping.

**Comment by daniellmb** [comment]
I tried it out and it's working like a charm! Although for those that read this later, the correct URL format is:

https://ga-beacon.appspot.com/UA-XXXXXXXX-X/event?t=event&ec=category&ea=action&el=label&ev=value
