### ISSUE TITLE
Flat style badge

### ISSUE THREAD

**Issue by paazmaya** [igrigorik/ga-beacon#19]
How about adding this to the available badges?

https://img.shields.io/badge/analytics-GA-blue.svg?style=flat-square

It looks like ![shields.io](https://img.shields.io/badge/analytics-GA-blue.svg?style=flat-square)

**Comment by igrigorik** [comment]
Sure. Want to make a pull request? :)

**Comment by paazmaya** [comment]
Sure!

**Comment by paazmaya** [comment]
Is there.

**Comment by leodido** [comment]
Flat style does not work.
