### ISSUE TITLE
Failed to compile and no traffic

### ISSUE THREAD

**Issue by hwdsl2** [igrigorik/ga-beacon#21]
Hello,

I would like to report two issues that I found yesterday:

1. The latest GitHub version fails to compile. It says error on line 152, "badgeFlatGit" is undefined. I reverted to commit 4d8960a in order for it to compile.
2. I tried using "ga-beacon.appspot.com", but no real-time traffic is registered in my Analytics Dashboard. I then pushed the code to my own GAE account and attempted to use it there. I tried Version 16 (4d8960a), 15 (f0dca65) and 12 (81f2a17). Unfortunately none of them showed any traffic in my dashboard as well. In other words the code is not working at all. Can you please check? By the way, the other "nojsstats.appspot.com" service works and traffic is shown in my dashboard.

Thank you for the awesome work!

**Comment by igrigorik** [comment]
Fixed the compile error in https://github.com/igrigorik/ga-beacon/commit/43a9c22a26dc8974db8efbbe5f03fc46ec6b04bd - thanks for the heads up.

I am seeing hits from ga-beacon.appspot.com in my own GA account. Are you sure you're setting the right property ID in your tests? Also, make sure you're using real-time analytics when checking for the hits.

**Comment by hwdsl2** [comment]
Thanks for the quick reply. I double checked my test configuration and they are fine. And I am indeed using the real-time analytics. 

I just ran the test again and observed something interesting: If I open this page directly in IE: https://ga-beacon.appspot.com/UA-XXXXXXXX-Y/ (the string is my Analytics property ID), I do see a hit registered in real-time dashboard. And the "active page" is shown as "/UA-XXXXXXXX-Y/". However, if I append anything to that URL, such as https://ga-beacon.appspot.com/UA-XXXXXXXX-Y/my-site/test-page , then no hit is registered in my real-time dashboard at all.

**Comment by hwdsl2** [comment]
I checked the Google Analytics forums and realized that because my GA property is brand new, there may be a delay of 24~72 hours before any data from the measurement protocol show up in my dashboard. 

Thanks again for your help - I'll report back if it still does not work after a few days. Otherwise I plan to close this issue.

**Comment by igrigorik** [comment]
@hwdsl2 the real-time tab in GA should show data in... real-time.

**Comment by monolithed** [comment]
+1, I don't see any traffic in my [project](https://github.com/Polyfiller/polyfiller)

![1432911660872](https://cloud.githubusercontent.com/assets/803674/7885478/b3a8a382-062c-11e5-96ac-d134257f9355.png)
![1432911628123](https://cloud.githubusercontent.com/assets/803674/7885479/b3ae6f38-062c-11e5-9c54-0082e23d9cf8.png)

**Comment by igrigorik** [comment]
@monolithed please check your real-time analytics.

Closing this bug since original issue was fixed.

**Comment by hwdsl2** [comment]
Finally found out the reason why ga-beacon was not working in my Analytics account. It boils down to changing a single setting in GA.

FYI for other people having this issue: You MUST UN-check the option "Exclude all hits from known bots and spiders" in the "View Settings" of your GA account. Otherwise no hits will be registered and the beacon won't work.

**Comment by igrigorik** [comment]
@hwdsl2 ah, that makes sense -- thanks for the heads up!

**Comment by Ragrant57** [comment]
Hi - I have just discovered GA-Beacon - thank you for creating it.

I'd like to use it to track traffic to my eBay product listings where I can't use js

I have installed the following line:

img src="https://ga-beacon.appspot.com/UA-7687050-3/ebay/test"

But when I visit the page, it is not showing up in my real-time stats in GA

Have I missed something?

Thanks for your help

**Comment by igrigorik** [comment]
@Ragrant57 first, make sure the image is actually included in the ebay page — you might have to inspect it. Per discussion above, uncheck the options mentioned above in GA and also see https://github.com/igrigorik/ga-beacon/issues/62
