### ISSUE TITLE
Not Showing Correct Ip Address

### ISSUE THREAD

**Issue by GrahamCampbell** [igrigorik/ga-beacon#22]
You're showing the IP of the GitHub proxy that loads the image instead of the user's IP address. Are your list of trusted proxies correctly configured so that you're reading the correct IP addresses?

**Comment by igrigorik** [comment]
Does GitHub's proxy communicate the client IP via an extra header, or some such? Currently it simply checks the remoteAddr value: https://github.com/igrigorik/ga-beacon/blob/master/ga-beacon/ga-beacon.go#L136

**Comment by GrahamCampbell** [comment]
I assume so, yeh. I haven't looked into it. I just tried out your service and all my traffic was showing as from the same location in America, so I assumed that was the cause.

**Comment by igrigorik** [comment]
@atmos does GitHub's camo deployment forward the client IP? Can't find anything in the docs: https://help.github.com/articles/why-do-my-images-have-strange-urls/

**Comment by atmos** [comment]
It does not, we [removed it](https://github.com/blog/1766-proxying-user-images) after we discovered that people were using it for client tracking last year.

**Comment by igrigorik** [comment]
@atmos interesting, thanks. In which case, closing this.. since there isn't much we can do here.

**Comment by GrahamCampbell** [comment]
We are using it for client tracking, lol...

**Comment by atmos** [comment]
@GrahamCampbell so... it's working in our user's best interest or have you guys found a way to circumvent it?
