### ISSUE TITLE
Does using ga-beacon violate the Google Analytics policy?

### ISSUE THREAD

**Issue by Alexander01998** [igrigorik/ga-beacon#26]
From the [Measurement Protocol policy](https://developers.google.com/analytics/devguides/collection/protocol/policy?hl=en):
> You will give your end users proper notice about the implementations and features of Google Analytics you use (e.g. **notice about what data you will collect via Google Analytics**, and whether this data can be connected to other data you have about the end user). You will either get consent from your end users, or **provide them with the opportunity to opt-out** from the implementations and features you use.

1. Especially when using the `?pixel` version, users will not be properly notified that they are being tracked by ga-beacon (although one could manually add a proper notice to the web page or email that is being tracked).

2. There is no way to opt-out of ga-beacon tracking, or is there?

---
Does that mean that using ga-beacon violates the Google Analytics / Measurement Protocol policy?

**Comment by igrigorik** [comment]
No, it does not. It simply says that as a developer you're responsible for notifying your users if, when, and how you're tracking their behavior in your apps... and providing opt-outs as necessary. The underlying collection mechanism is orthogonal (ga-beacon or anything else).

**Comment by Alexander01998** [comment]
Thank you for making that clear. :+1:

Now how would I go about providing an opt-out for ga-beacon to my users? Would installing the Google Analytics opt-out browser plugin work (considering that ga-beacon tracking on GitHub uses a proxy to load the tracking image)?

**Comment by igrigorik** [comment]
Not familiar with that plugin -- maybe, maybe not. You could also add code on your side that omits inserting the tracker based on user preference.

**Comment by Alexander01998** [comment]
> Not familiar with that plugin -- maybe, maybe not.

If it helps, here is a link to the plugin: https://tools.google.com/dlpage/gaoptout/

> You could also add code on your side that omits inserting the tracker based on user preference.

I cannot do that, because I am using it on the README.md files of my GitHub repositories.

**Comment by igrigorik** [comment]
In which case you should add a note explaining that the tracker is being used. The user can adjust their settings to block that request, if they wish.. E.g. via adblock or something else.
