### ISSUE TITLE
Dashboard shows referrer and no page data

### ISSUE THREAD

**Issue by angryloner** [igrigorik/ga-beacon#28]
This is all I get in my dashboard when using this from a google spreadsheet.

The referrer url leads to a shopping site and is apparently from Russia.

Not sure if the script has been compromised or I am having a different issue.

I using the following formula in a google spreadsheet:

=IMAGE("https://ga-beacon.appspot.com/UA-XXXXXX-X/alasdairs-week/aug-14")

![image](https://cloud.githubusercontent.com/assets/947697/9216042/a022eb6a-40f6-11e5-8609-244a7f811844.png)

Thanks for any clues,
Alasdair

**Comment by igrigorik** [comment]
AFAIK, that's not sufficient as the beacon image will be cached. See https://mashe.hawksey.info/2014/02/tracking-google-sheet-views-with-google-analytics/
