### ISSUE TITLE
HTTPS vs HTTP

### ISSUE THREAD

**Issue by JHGrove3** [igrigorik/ga-beacon#29]
Is it important that the request for the image be made via HTTPS, or does HTTP work equally well?

I'm considering using this to help track email open rates, and I'm thinking that an HTTP image request is less likely to have any kind of security warnings than is an HTTPS request.

**Comment by heynemann** [comment]
It also won't open in an https environment (usually all the e-mail providers). Thumbor won't care whether the image you are using is http or https, though.

**Comment by igrigorik** [comment]
You should always request the HTTPS resource: protects user privacy; doesn't break when a web mail client is accessed over HTTPS (otherwise it would be blocked due to mixed content).

**Comment by JHGrove3** [comment]
Thanks for the tip.  Can you point me towards some resources that would show me how to set up my own appengine install for this?  I'd like to be able to use a branded logo, and I'd like to have a branded URL, too.

**Comment by igrigorik** [comment]
@JHGrove3 follow the steps in: https://cloud.google.com/appengine/docs/go/gettingstarted/uploading - except, you want to check out this repo, rename the project to your own name... and upload. That's basically it.
