### ISSUE TITLE
Issue with beacon?

### ISSUE THREAD

**Issue by victoriafrench** [igrigorik/ga-beacon#38]
I have a beacon installed on project cinecove/defunctr here at github. It's been on the readme.md page for a few days now (around 5). Google Analytics is not recording any traffic though. Nothing at all. I have verified that the url is set correct and that the id is correct. Am I missing something I should be checking? 

Thanks

**Comment by igrigorik** [comment]
Unfortunately this is due to a change in how GitHub serves images. I've updated the readme to address this: https://github.com/igrigorik/ga-beacon/commit/6acd8627bb7be36f24f5516e9873c92719a50e55

**Comment by hwdsl2** [comment]
@victoriafrench See my comment in #21.

**Comment by victoriafrench** [comment]
@hwdsl2 thanks! unfortunately any hit to ga-beacon is reporting a 503 Over Quota error, so I will test it when the server goes back online, or just throw the code up on EC2 and run my own instance.

**Comment by victoriafrench** [comment]
@hwdsl2 the site came back up and it's working now, including the readme.md. Thanks much!
