### ISSUE TITLE
GA-Beacon appears to be over quota

### ISSUE THREAD

**Issue by markmcd** [igrigorik/ga-beacon#39]
Looks like App Engine isn't happy, e.g. https://ga-beacon.appspot.com/UA-12846745-20/google-maps-services-java/readme?pixel displays a web page with this text:

> Over Quota
> 
> This application is temporarily over its serving quota. Please try again later.

**Comment by jonathansides** [comment]
Thank you for posting this issue report, Mark! I was struggling to understand why GA was not showing my Google Sheet views and your answer cleared it up. I will now try to set up the code on my own instance of Google App Engine like Ilya suggests at the bottom of the instructions.

**Comment by gregmoser** [comment]
Looks like daily this is going over the quota limit.  I'm noticing that the image breaks on my github repo every afternoon.

**Comment by Guisardo** [comment]
Hi all, remember that you could easily create your own api from this project using the google cloud platform. And is free (if you don't exceed your own quota).
https://cloud.google.com/appengine/docs/python/gettingstartedpython27/uploading
https://cloud.google.com/appengine/docs/quotas?hl=en_US

**Comment by gregmoser** [comment]
@Guisardo, thanks for brining up that point, and actually right after I posted to this issue I actually did set it up on my own instance on google cloud.  That process works great and it's super easy to setup.

**Comment by igrigorik** [comment]
@gregmoser :+1:

This service is meant as a demo, not an official GA endpoint. @markmcd please consider running your own instance. This is a wontfix on this end.
