### ISSUE TITLE
ga-beacon hits now blocked with GA bot filtering?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [igrigorik/ga-beacon#42]
Hello,

I've been using this beacon recently, and have seen that the hits only show on a View that does not have "Bot Filtering?" option checked.  Thats the only difference between the Raw and normal view. 

David Vallejo [suggested it may have something to do with the headers](https://twitter.com/thyng/status/706384897955344388) that are sent with the request?  

This also seems to have started recently, perhaps related to changes with how GA handles spam event bots?

**Comment by vitr** [comment]
I believe, recently github started using proxy for serving images, e.g
`<img src="https://camo.githubusercontent.com/30b62c40871935ce7d4b98bae84dce3cec1ba9b3/68747470733a2f2f67612d626561636f6e2e61707073706f742e636f6d2f55412d37313139362d31302f67612d626561636f6e2f726561646d653f706978656c" alt="Analytics" data-canonical-src="https://ga-beacon.appspot.com/UA-71196-10/ga-beacon/readme?pixel" style="max-width:100%;">`
note **camo.githubusercontent.com**, and you can see only
`BROWSER: Camo Asset Proxy 2.2.0 AppEngine-Google;` 
in Google analytics. I guess, ga-beacon isn't useful for github anymore.

**Comment by igrigorik** [comment]
@MarkEdmondson1234 good question, not sure.. @philipwalton any insights on this one?

@vitr yeah, that's a separate topic, see: https://github.com/igrigorik/ga-beacon/commit/6acd8627bb7be36f24f5516e9873c92719a50e55

**Comment by philipwalton** [comment]
I assume it's probably related to some sort of spam filtering, but I don't know for sure. I'll look into it.

@MarkEdmondson1234 I'm sure you already know this, but you could turn off bot filtering and add your own filter that's probably as or more effective.

@igrigorik maybe this isn't possible anymore if what @vitr is saying is true (Github proxying img urls), but with GA it's possible to use [UA and IP overrides](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#using-a-proxy-server), which might also help make the hits not seem so bot-like. Using the UA and IP overrides will also allow these hits to have the proper GEO and browser data in GA.

**Comment by LindaLawton** [comment]
Little update on this. @MarkEdmondson1234  spoke to the GA Dev team and this is being looked into on their side.     The answer we got from them is that it is possible that things are being blocked.

**Comment by igrigorik** [comment]
@philipwalton we do set the IP and UA overrides:
- https://github.com/igrigorik/ga-beacon/blob/master/ga-beacon/ga-beacon.go#L83
- https://github.com/igrigorik/ga-beacon/blob/master/ga-beacon/ga-beacon.go#L58

@MarkEdmondson1234 any updates on this one? Anything actionable for ga-beacon?

**Comment by MarkEdmondson1234** [comment]
@igrigorik all I can report is that using bot filtering still prevents these hits appearing in the GA account with bot filtering turned on.  I don't think there is much that can be done your end.

As an example, I use the beacon at the bottom of this URL http://markedmondson.me/enhance-your-google-analytics-data-with-r-and-shiny-free-online-dashboard-template and see 389 hits in the raw data profile, none in the bot filtered one.  

It won't work on Github anymore due to the image hosting, but its still useful for me to get a quick measurement for lots of users into one account where you can host the image.

**Comment by igrigorik** [comment]
@MarkEdmondson1234 thanks for the update, makes sense.

Re, GitHub: there may be a workaround.. see https://github.com/igrigorik/ga-beacon/issues/47. 

That said, closing this thread, as there is nothing ga-beacon actionable here.
