### ISSUE TITLE
Google Analytics now providing its own beacons?

### ISSUE THREAD

**Issue by good-kiwi** [igrigorik/ga-beacon#43]
I used this project to setup some beacons, but realized recently that google now can host its own beacons from its measurement protocol - see here: https://developers.google.com/analytics/devguides/collection/protocol/v1/email#overview

I think ga-beacon is still useful if you would like to intercept and store data on your own server but also report it to google analytics, but it is probably better if you want simple beacons to just use google's version directly.

**Comment by igrigorik** [comment]
@good-kiwi see second point in the FAQ: https://github.com/igrigorik/ga-beacon#faq - we use the collector protocol under the hood, but that's not sufficient on its own.
