### ISSUE TITLE
503 Over Quota

### ISSUE THREAD

**Issue by cyhsutw** [igrigorik/ga-beacon#44]
Visiting https://ga-beacon.appspot.com/UA-71196-10/ga-beacon/readme?pixel is showing an error page like this:

![503](https://cloud.githubusercontent.com/assets/1046917/15137924/20a30c0e-16bf-11e6-9435-6adce6dc0c86.png)

Not sure what kind of quota is running out. Will the site be up again after few hours or few days?

Thanks

**Comment by vitr** [comment]
oh, man, it goes over quota almost everyday)) you better setup your own instance on GAE, if you don't know how, I've got some tips here https://github.com/vitr/google-analytics-beacon

**Comment by cyhsutw** [comment]
Thanks @vitr!
I'll set up my own instance by following the instruction of your repo 🆒
