### ISSUE TITLE
geo location not correct. 

### ISSUE THREAD

**Issue by zeeev** [igrigorik/ga-beacon#45]
Thanks for making ga-beacon.  In my GA dashboard it appears that all my traffic is routing through one location.  Is it not possible to get accurate geo info?

**Comment by igrigorik** [comment]
We do report the IP address of the user: 
- https://github.com/igrigorik/ga-beacon/blob/master/ga-beacon/ga-beacon.go#L83
- https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#uip

Geo reporting should work.

**Comment by zeeev** [comment]
Hmm, i'll chalk it up to something i'm doing wrong.  I live in WA and all the traffic is coming from VA.
