### ISSUE TITLE
Tracking Code Mismatch alert on GA

### ISSUE THREAD

**Issue by ahmetalpbalkan** [igrigorik/ga-beacon#46]
I got an alert like this on Google Analytics:

![image](https://cloud.githubusercontent.com/assets/159209/16498138/283a72be-3eaf-11e6-813d-8c459079c180.png)

And I have the beacon code with the correct tracking ID:

```
![Analytics](https://ga-beacon.appspot.com/UA-45321252-5/welcome-page)
```

any ideas what might be happening?

**Comment by ahmetalpbalkan** [comment]
Looks similar to #30. I just updated my URL from:

![image](https://cloud.githubusercontent.com/assets/159209/16498221/8c20ecb8-3eaf-11e6-9bc0-281498970d19.png)

to 

![image](https://cloud.githubusercontent.com/assets/159209/16498227/93889d52-3eaf-11e6-9d0b-e9ac910b2fa5.png)

I'll close this issue if this fixes the problem.

**Comment by igrigorik** [comment]
Closing, please reopen if this still an issue.
