### ISSUE TITLE
Not working for spreadsheets

### ISSUE THREAD

**Issue by sajuuk111** [igrigorik/ga-beacon#48]
Greets, i have been using it at my spreadsheet, but stopped working. I haven't changed anything, it just stopped working. Double checked everything, made a new spreadsheet, used even example one, no. It just stopped working and cant get it to work.

https://mashe.hawksey.info/2014/02/tracking-google-sheet-views-with-google-analytics/

Taken information from there.

https://docs.google.com/spreadsheets/d/1TXym5_hkoGBOhB9lWucAcAv4-7MWY50zzSJBILYa0Bs/edit#gid=0

This is the one  i have used for testing, if you could help, much appreciated.

**Comment by igrigorik** [comment]
It appears that the demo instance is hitting its daily free quota limits on AppEngine, which is most likely why you're seeing this.  Note that the demo instance is just that.. a demo, no reliability guarantees. 

A simple fix is for you to deploy own GAE instance, the free tier should be plenty for most use cases.

**Comment by sajuuk111** [comment]
@igrigorik thanks for the fast reply! It's working now. Could you tell me what do you mean by "deploy your own GAE instance" by no means i'm a programmer and close to these topics, but if it is an easy thing to do, i will try to get my friends to work on that

**Comment by vitr** [comment]
@sajuuk111 hey, I explain the issue here https://github.com/vitr/google-analytics-beacon if it's easy for you to follow, get your own instance of the beacon.

**Comment by sajuuk111** [comment]
@vitr Thank you so much for that. I'm trying to get it work. I have forked it, but when i write this

> cd ~/src/concise-ion-147213/master

that's my project id btw, it returns as " no file or directory found " , what's wrong there?
