### ISSUE TITLE
Adding image to a google doc file.

### ISSUE THREAD

**Issue by inheritanceXIV** [igrigorik/ga-beacon#49]
Hi, 

Im having trouble adding the URL to my google docs. I have confirmed that

https://ga-beacon.appspot.com/UA-87927789-1/CorsairManual

does send a tag to my google account but I cant seem to get the image inserted.

**Comment by igrigorik** [comment]
AFAIK, this method will not work with Google Docs, because docs caches the image response.

**Comment by inheritanceXIV** [comment]
I see. So you know a method that would work in google docs by any chance?

**Comment by igrigorik** [comment]
Unfortunately.. no. If you stumble across a solution, please let me know!

**Comment by inheritanceXIV** [comment]
Will do, ty for your time.
