### ISSUE TITLE
Request for using your service for 20 million pages views per year

### ISSUE THREAD

**Issue by Ouaps** [igrigorik/ga-beacon#50]
Sorry for getting in touch via this forum. 
We intend to use your service for a few months and this might cause an overload. Knowing that you cannot guarantee the service will run properly in the long run in case of overload, we wanted to make sure it is ok for you if we use your service for an estimated 20 million page views a year ?
Looking forward to hearing from you,
Regards.
Thank you for letting us know if that's of any problem for you

**Comment by igrigorik** [comment]
@Ouaps please see https://github.com/igrigorik/ga-beacon/blob/master/README.md#can-i-use-this-production. Thanks!
