### ISSUE TITLE
Custom Badge/Image

### ISSUE THREAD

**Issue by imsus** [igrigorik/ga-beacon#53]
First of all, thank you for creating this repo.

I just want to add some ideas that is custom image which can derived from the url.

Like this example
```
<img src="https://ga-beacon.appspot.com/UA-XXXX-X/landing-page?image=https://example.com/example.jpg">
```
Which will fetch image from the specified url replacing the badge.
Or maybe we can implement from the app itself.

Thank you. And once again, it's just idea.

**Comment by igrigorik** [comment]
This would imply that the beacon has to proxy arbitrary content from third-party origins, which is both very costly and not necessarily safe. I'm inclined to say that this is not something we want to support or enable.

Thanks for the suggestion!
