### ISSUE TITLE
How works this with Camo?

### ISSUE THREAD

**Issue by mcuadros** [igrigorik/ga-beacon#59]
GitHub is use Camo to cache the images, how accurate is the tracking information when the image is not served directly?

https://help.github.com/articles/about-anonymized-image-urls/
> hides your browser details and related information from other users.

**Comment by igrigorik** [comment]
See https://github.com/igrigorik/ga-beacon/commit/6acd8627bb7be36f24f5516e9873c92719a50e55

**Comment by mcuadros** [comment]
Thanks
