### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by andrekosak** [igrigorik/ga-beacon#62]
Since few days i get no data from beacon images to analytics. Anyone else has same problem?

**Comment by andrekosak** [comment]
oh, now it's working again.

**Comment by maxoptical** [comment]
I am having an issue that they tracking stops every day at 2:00PM EST.  Then restarts and 3:00AM

**Comment by igrigorik** [comment]
This is due to too many folks using the demo instance for their production deployments. I would recommend deploying own (free) instance to ensure that you have enough capacity.

**Comment by maxoptical** [comment]
worked like a champ,  thank you again.
