### ISSUE TITLE
Analytics are logging excluded (filtered) IP

### ISSUE THREAD

**Issue by Joohansson** [igrigorik/ga-beacon#63]
I always put in my own IP in google analytics filter settings as exclusion from the stats. This work on my other sites. It seems this tracking code is logging the traffic anyway but it seems to know correct country. I don't understand? It says in your description in can detect unique users and IP?

**Comment by igrigorik** [comment]
You can see the proxied payload here: https://github.com/igrigorik/ga-beacon/blob/master/ga-beacon.go#L78-L85. It includes the IP address that's making the request to ga-beacon endpoint. 

So, if you're making a request through ga-beacon, your IP should be proxied to GA and your rules should apply.

**Comment by Joohansson** [comment]
Very strange then because I removed the beacon and used jekyll seo plugin instead with google analytics and my IP was filtered straight ahead without changing any filters! Something was not working correct.
