### ISSUE TITLE
Is it possible to use ga-beacon in gist?

### ISSUE THREAD

**Issue by doc-hub** [igrigorik/ga-beacon#66]
I have read [remove github example from readme · igrigorik/ga-beacon@6acd862](https://github.com/igrigorik/ga-beacon/commit/6acd8627bb7be36f24f5516e9873c92719a50e55), but also found the instructions below from [Gistguide.github.io by wallydrag](https://wallydrag.github.io/gist_guide/) and similar content from somewhere else. I guess the posts and blogs are out-dated or wrong, is that true?

### 9. Measure the Traffic

You can use Google Analytics to measure the traffic to your Gists. Since Github does not allow JavaScript code to run inside plain text Gists, we can use the GA Beacon https://github.com/igrigorik/ga-beacon to log visits in real-time to Gists.

Add this line to your Gists, save in Markdown format and it will add a transparent tracking image to your Gists.

```
![Analytics](https://ga-beacon.appspot.com/UA-XXXXX-X/gist-id?pixel)
```

**Comment by igrigorik** [comment]
Gists: yes, GitHub rewrites and proxies image assets so same as rendering a readme file on your repo, etc. Your beacon _will_ gather some data but it won't be 100% accurate because there is caching, etc.
