### ISSUE TITLE
Cross Domain Tracking Support

### ISSUE THREAD

**Issue by jmwebservices** [igrigorik/ga-beacon#67]
I just came across this repo. Is cross domain tracking possible? We provide web services to financial institutions and we would like to record "conversions" that start on their website but _actually_ convert on a third-party web app. Although the web app allows us to use GA, they do not allow us to modify the snippet at all.

Thanks!

**Comment by igrigorik** [comment]
No, I don't think so.. This is a thin wrapper around GA that would require modifying the page.
