### ISSUE TITLE
Using GA-Beacon in Cross-Domain Environment

### ISSUE THREAD

**Issue by JHGrove3** [igrigorik/ga-beacon#9]
Hi, Ilya -

Thanks for building such a handy tool!

I'm experimenting with it as a way to help measure traffic to partner pages that won't run my Google Tag Manager code.

I currently use the Tag Manager and Google Analytics on multiple domains, so that I can view visitors as they travel between my various related websites.

For this reason, I want to be able to capture the domain name as well as the page name and path.  I then have a filtered view that includes the domain name in the GA reporting, so I can tell what site the page is on.

https://support.google.com/analytics/answer/1034342?hl=en 

I notice that GA-Beacon puts a slash ("/") at the front of the page name, but it does not include the domain information.  So it looks correct in a single-domain GA setup, but does not work as cleanly in a cross-domain environment where it puts a slash in front of the domain name I include in my beacon URL.

It would be great if the tool could accommodate including a domain in the URL, and somehow pass that information through to GA correctly.

**Comment by igrigorik** [comment]
This should be available now, via: http://ga-beacon.appspot.com/account/UA-XXXXX-X/page-name?dh=foo.com
